export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const GET_TOURS_RAW_SUCCESS = "GET_TOURS_RAW_SUCCESS";
export const GET_TOURS_RAW_FAIL = "GET_TOURS_RAW_FAIL";
