export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const LOG_OUT = "LOG_OUT";

export const GET_TOURS_RAW_SUCCESS = "GET_TOURS_RAW_SUCCESS";
export const GET_TOURS_RAW_FAIL = "GET_TOURS_RAW_FAIL";

export const TOUR_CATS_GET_ALL_SUCCESS = "TOUR_CATS_GET_ALL_SUCCESS";
export const TOUR_CATS_GET_ALL_FAIL = "TOUR_CATS_GET_ALL_FAIL";

export const TOUR_CATS_CONFIG_GET_SUCCESS = "TOUR_CATS_CONFIG_GET_SUCCESS";
export const TOUR_CATS_CONFIG_GET_FAIL = "TOUR_CATS_CONFIG_GET_FAIL";

export const TOUR_CATS_CONFIG_CREATE_SUCCESS =
  "TOUR_CATS_CONFIG_CREATE_SUCCESS";
export const TOUR_CATS_CONFIG_CREATE_FAIL = "TOUR_CATS_CONFIG_CREATE_FAIL";

export const TOUR_CAT_EDIT_SUCCESS = "TOUR_CAT_EDIT_SUCCESS";
export const TOUR_CAT_EDIT_FAIL = "TOUR_CAT_EDIT_FAIL";

export const TOUR_CAT_DELETE_SUCCESS = "TOUR_CAT_DELETE_SUCCESS";
export const TOUR_CAT_DELETE_FAIL = "TOUR_CAT_DELETE_FAIL";

export const TOUR_BOOK_CREATE_SUCCESS = "TOUR_BOOK_CREATE_SUCCESS";
export const TOUR_BOOK_CREATE_FAIL = "TOUR_BOOK_CREATE_FAIL";

export const TOUR_BOOK_GET_ALL_SUCCESS = "TOUR_BOOK_GET_ALL_SUCCESS";
export const TOUR_BOOK_GET_ALL_FAIL = "TOUR_BOOK_GET_ALL_FAIL";

export const TOURS_GET_ALL_SUCCESS = "TOURS_GET_ALL_SUCCESS";
export const TOURS_GET_ALL_FAIL = "TOURS_GET_ALL_SUCCESS";

export const TOUR_EDIT_SUCCESS = "TOUR_EDIT_SUCCESS";
export const TOUR_EDIT_FAIL = "TOUR_EDIT_FAIL";

export const TOUR_DELETE_SUCCESS = "TOUR_DELETE_SUCCESS";
export const TOUR_DELETE_FAIL = "TOUR_DELETE_FAIL";

export const TOUR_CONFIG_GET_SUCCESS = "TOUR_CONFIG_GET_SUCCESS";
export const TOUR_CONFIG_GET_FAIL = "TOUR_CONFIG_GET_SUCCESS";

export const TOUR_CONFIG_CREATE_SUCCESS = "TOUR_CONFIG_CREATE_SUCCESS";
export const TOUR_CONFIG_CREATE_FAIL = "TOUR_CONFIG_CREATE_SUCCESS";
